version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true 
      - FAST_REFRESH=false
      - WDS_SOCKET_PORT=30000
    ports:
      - 3000:3000
    volumes:
      - ./:/frontend

volumes:
  db_volume:
    external: true