name: CD

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-test:
    name: check lint and run build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
  docker-build:
    name: Build and publish to registry
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          push: true
          target: production
          tags: lowesilvan/social:prod${{ github.run_number }}
  deploy:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: deploy to prod
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home
            docker compose down
            docker image prune -a --force
            TAG=prod${{ github.run_number }} docker compose up -d
      - name: Successfully Deployed to Prod
        run: echo "Successfully deployed prod${{ github.run_number }}"